apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: ludovic
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: name
    - name: OWNER
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: owner
