kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-nfs
  namespace: forma-madiba
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
