apiVersion: v1
kind: Service
metadata:
  name:  frontend
spec:
  clusterIP: 
  selector:
    app: web
  type: LoadBalancer
  ports:
    - port: 80
status:
  loadBalancer:
    ingress:
    - ip: 172.42.42.242
