apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    app: demo
    namespace: forma-madiba
spec:
  containers:
  - image: quenec/liveness:latest
    name: liveness
    livenessProbe:
      httpGet:
        path: /sonde
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 2
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
