apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db-data
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
