apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-mariadb
  namespace: ludo-forma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
