apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: web
  name: web
  namespace: ludo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        name: nginx
