apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  annotations:
    kubernetes.io/change-cause: "Versiob 1.10"
  name: nginx-deploy
  namespace: ludo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx:1.10
        name: nginx
