apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  namespace: forma-madiba
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
