apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apache-php
  namespace: ludo-forma
  labels:
    name: apache-php
spec:
  endpoints:
  - interval: 5s
    port: web
  selector:
    matchLabels:
      app: apache-php
