apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-data-1
  namespace: forma-madiba
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
