apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: #votre namespace
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
