apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: automic-role
rules:
  -apiGroups:
      -extensions
   resourceNames:
      -pks-privileged
   resources:
      -podsecuritypolicies
   verbs:
      -use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: automic-rolebinding
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: automic-role
subjects:
  -kind: Group
   apiGroup: rbac.authorization.k8s.io
   name:system: serviceaccounts
