apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: ludo
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
